apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-regcred
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: ghcr-regcred
  dataFrom:
  - extract:
      key: /ghcr
