name: pr

on:

  pull_request:
    branches:
      - main

jobs:

  helm-quality:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/github-release.yaml@main
    secrets: inherit
    with:
      helm_path: helm
  
  preview-helm-quality:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/github-release.yaml@main
    secrets: inherit
    with:
      helm_path: preview/helm

  preview:
    needs: helm-quality
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3
    
    - name: Checkout Preview Environments Project
      uses: actions/checkout@v3
      with: 
        path: previews
        repository: cloudnativeentrepreneur/example-preview-envs
        persist-credentials: false

    - name: Create Preview from Helm template
      run: |
        mkdir -p previews/helm/templates
        helm template preview/helm/ \
          --set pr=pr-${{ github.event.pull_request.number }} \
          --set tag=pr-${{ github.event.pull_request.number }}-${{ github.sha }} \
          --set headRef=${{ github.head_ref }}  \
          --set name=${{ github.event.repository.name }} \
          > previews/helm/templates/${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.yaml

    - name: Commit Preview Env Changes
      run: |
        cd previews

        if output=$(git status --porcelain) && [ -z "$output" ]; then
          # Working directory clean

          echo "No changes to commit"
        else 
          # Uncommitted changes

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"   
          git add -A
          git commit -m "promote: ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }} ${{ github.sha }}"
        fi

        

    - name: Push Preview Env Changes
      uses: ad-m/github-push-action@master
      with:
        directory: previews
        github_token: ${{ secrets.GH_ORG_TOKEN }}
        repository: cloudnativeentrepreneur/example-preview-envs

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Your preview environment

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Your preview environment has been published! :rocket:

          It may take a few minutes to spin up.

          You can view the Preview contents with `kubectl`:

          ```bash
          kubectl get ns ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}-preview
          kubectl get sa -n ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}-preview
          kubectl get externalsecret -n ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}-preview
          ```
        edit-mode: replace
